services:

  redis:
    build: ./redis
    image: aether-redis:latest
    container_name: aether-redis
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/data:/data
    networks:
      - aether

  mariadb:
    build: ./mariadb
    image: aether-mariadb:latest
    container_name: aether-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: bridge
    volumes:
      - ./mariadb/data:/var/lib/mysql
    networks:
      - aether

  phpmyadmin:
    build: ./phpmyadmin
    image: aether-pma:latest
    container_name: aether-pma
    restart: unless-stopped
    ports:
      - "51234:80"
    depends_on:
      - mariadb
    networks:
      - aether

  mongodb:
    build: ./mongodb
    image: aether-mongodb:latest
    container_name: aether-mongodb
    restart: unless-stopped
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - aether

  minecraft:
    build:
      context: ./minecraft
      args:
        # 用于 amd64 架构的 JDK, 按需修改
        JDK_AMD64_URL: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-21.0.6-linux-x64-b872.85.tar.gz
        # 用于 arm64 架构的 JDK, 按需修改
        JDK_ARM64_URL: https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-21.0.6-linux-aarch64-b872.85.tar.gz
    image: aether-minecraft:latest
    container_name: aether-mc
    ports:
      - "30000:25565" # router
      - "30001:25566" # proxy
      - "7270:7270" # resourcepack server
      - "10005:10005" # jdwp for router
      - "10006:10006" # jdwp for proxy
      - "11005:11005" # jdwp for game1
      - "11006:11006" # jdwp for game2
      - "11007:11007" # jdwp for game3
      - "11008:11008" # jdwp for game4
    depends_on:
      - redis
      - mariadb
      - mongodb
    volumes:
      - ./minecraft/app:/minecraft
    networks:
      - aether

networks:
  aether:
    driver: bridge
