FROM ubuntu:noble

ARG TARGETPLATFORM
ARG JDK_AMD64_URL
ARG JDK_ARM64_URL
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
  curl \
  jq \
  tar \
  unzip \
  tmux \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/jdk && \
  if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
  curl -L $JDK_AMD64_URL -o /tmp/jdk-x64.tar.gz && \
  tar -xzf /tmp/jdk-x64.tar.gz -C /opt/jdk --strip-components=1 && \
  rm /tmp/jdk-x64.tar.gz; \
  elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
  curl -L $JDK_ARM64_URL -o /tmp/jdk-arm64.tar.gz && \
  tar -xzf /tmp/jdk-arm64.tar.gz -C /opt/jdk --strip-components=1 && \
  rm /tmp/jdk-arm64.tar.gz; \
  else \
  echo "Unsupported architecture: $TARGETPLATFORM" 1>&2; \
  exit 1; \
  fi

ENV JAVA_HOME=/opt/jdk
ENV PATH=$JAVA_HOME/bin:$PATH

# 最后直接执行一下 java 指令, 如果没报错则说明安装成功
RUN java -version
