FROM nginx:1

COPY conf/sites-enabled/ /etc/nginx/sites-enabled
COPY conf/nginx.conf /etc/nginx/nginx.conf

COPY www/ /var/www

# Ensure nginx can write to the web root
RUN chown -R nginx:nginx /var/www
RUN chmod -R 777 /var/www
