-- 该用户给各服务使用
CREATE USER IF NOT EXISTS 'minecraft'@'%' IDENTIFIED BY 'A123456789a';
GRANT ALL PRIVILEGES ON *.* TO 'minecraft'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS phpmyadmin;
